import { siteConfig } from '../config/siteConfig'
import { trackConversion, trackWhatsAppClick, withCampaign } from '../utils/analytics'
import { products } from '../data/products'
import styles from './CampaignPage.module.css'

function CampaignPage({ campaign }) {
  const product = products.find((item) => item.id === campaign.productId)
  const url = `https://wa.me/${siteConfig.whatsappNumber}?text=${encodeURIComponent(withCampaign(`Olá, Ronael. Quero saber mais sobre o ${product.name} para o meu negócio.`))}`
  function click(event) { event.preventDefault(); const currentUrl = `https://wa.me/${siteConfig.whatsappNumber}?text=${encodeURIComponent(withCampaign(`Olá, Ronael. Quero saber mais sobre o ${product.name} para o meu negócio.`))}`; window.open(currentUrl, '_blank', 'noopener,noreferrer'); trackWhatsAppClick(`campaign_${product.id}`); trackConversion('campaign_cta', { product: product.id }) }
  const notFor = product.id === 'presenca-essencial' ? 'Para quem já precisa de um sistema interno, catálogo complexo ou área restrita.' : 'Para quem busca automação total, promessa de resultado garantido ou uma ferramenta sem participação na implantação.'
  return <><header className={styles.header}><a href="/"><img src={siteConfig.logoPath} alt="Ronas Tech" width="42" height="40" /><span>Ronas Tech</span></a><a className={styles.headerCta} href={url} target="_blank" rel="noopener noreferrer" onClick={click}>Falar no WhatsApp</a></header><main className={styles.main}><section className={styles.hero}><p className={styles.eyebrow}>Solução prática Ronas Tech</p><h1>{campaign.title}</h1><p>{campaign.description}</p><div className={styles.price}>a partir de <strong>{product.price}</strong></div><a className={styles.cta} href={url} target="_blank" rel="noopener noreferrer" onClick={click}>Quero organizar meu negócio <span aria-hidden="true">↗</span></a></section><section className={styles.proof}><div className={styles.mockup} aria-label="Exemplo visual da entrega" role="img"><span /><span /><span /><strong>{product.name}</strong><small>Estrutura simples para acompanhar o dia a dia</small><i /><i /><i /></div><div><h2>O resultado prático esperado</h2><p>Uma estrutura mais clara para executar esta etapa da rotina. O resultado depende do uso e do contexto do negócio; a entrega é ajustada antes do início.</p><a className={styles.cta} href={url} target="_blank" rel="noopener noreferrer" onClick={click}>Falar sobre esta solução <span aria-hidden="true">↗</span></a></div></section><section className={styles.details}><div><h2>O que esta solução resolve</h2><p>{product.solves}</p><h2>Para quem é</h2><p>{product.audience}</p><h2>Para quem não é</h2><p>{notFor}</p></div><div className={styles.card}><h2>Escopo da entrega</h2><ul>{product.items.map((item) => <li key={item}>{item}</li>)}</ul></div></section><section className={styles.hiring}><h2>Como funciona a contratação</h2><ol><li>Você explica o cenário pelo WhatsApp.</li><li>Revisamos o escopo, valores e eventuais custos de terceiros.</li><li>Com a aprovação, combinamos entrada, etapas e orientação de entrega.</li></ol></section><section className={styles.faq}><h2>Perguntas rápidas</h2><details><summary>Preciso contratar alguma ferramenta mensal?</summary><p>Não. A proposta é começar com uma solução prática usando recursos adequados ao seu negócio. Custos de terceiros, quando existirem, são explicados antes.</p></details><details><summary>Posso adaptar a entrega?</summary><p>Sim. O escopo é revisado com você antes do início para manter o projeto proporcional à necessidade.</p></details><details><summary>Vocês prometem um resultado específico?</summary><p>Não. A Ronas Tech entrega uma estrutura clara e orientação; o resultado depende da aplicação no contexto de cada negócio.</p></details></section><section className={styles.finalCta}><h2>Quer avaliar se faz sentido para você?</h2><a className={styles.cta} href={url} target="_blank" rel="noopener noreferrer" onClick={click}>Falar no WhatsApp <span aria-hidden="true">↗</span></a></section></main></>
}
export default CampaignPage
