import { siteConfig } from '../config/siteConfig'
import styles from './PersonalFinanceProductPage.module.css'
import fixes from './PersonalFinanceProductPageFixes.module.css'

const whatsappUrl = `https://wa.me/${siteConfig.whatsappNumber}?text=${encodeURIComponent('Olá! Quero comprar o Kit Financeiro Inteligente para MEI por R$ 37,90.')}`
const benefits = [
  ['Controle sem confusão', 'Registre receitas e despesas em poucos campos e mantenha tudo no mesmo lugar.'],
  ['Visão clara do negócio', 'Veja faturamento, gastos, lucro, margem e pendências em um painel automático.'],
  ['Preço calculado com lógica', 'Inclua custos, taxas, impostos e margem para encontrar um preço sustentável.'],
  ['Rotina mais organizada', 'Acompanhe vencimentos e identifique rapidamente contas atrasadas.'],
]
const included = ['Planilha financeira empresarial para MEI','Controle de contas a pagar e receber','Dashboard anual com gráficos automáticos','Calculadora de precificação','Categorias personalizáveis','Manual ilustrado de uso']
const previews = [['/kit-mei-dashboard.png','Dashboard financeiro anual'],['/kit-mei-lancamentos.png','Lançamentos financeiros'],['/kit-mei-precificacao.png','Calculadora de precificação']]

function BuyButton(){return <a className={`${styles.buyButton} ${fixes.buyButton}`} href={whatsappUrl} target="_blank" rel="noopener noreferrer">Quero o Kit Financeiro</a>}

function KitFinanceProductPage(){return <div className={styles.page}>
  <header className={styles.header}><a className={styles.brand} href="/"><img src={siteConfig.logoPath} alt="" width="48" height="45"/><span><strong>Ronas Tech</strong><small>Planilhas inteligentes</small></span></a><nav aria-label="Navegação da página"><a href="/#produtos-digitais">Ver outros produtos</a><a className={styles.headerCta} href={whatsappUrl} target="_blank" rel="noopener noreferrer">Comprar agora</a></nav></header>
  <main id="conteudo-principal">
    <section className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}>Finanças organizadas para MEI</p><h1>Kit Financeiro Inteligente para MEI</h1><p className={styles.lead}>Saiba quanto entra, quanto sai e quanto realmente sobra. Controle o caixa, calcule preços e enxergue seu negócio com mais clareza.</p><div className={styles.trustRow}><span>✓ Planilha Excel</span><span>✓ Manual ilustrado</span><span>✓ Pagamento único</span></div><div className={styles.offer}><div><small>POR APENAS</small><strong><span>R$</span> 37,90</strong><p>sem mensalidade</p></div><BuyButton/></div></div><div className={styles.heroVisual}><div className={styles.deviceDesktop}><span/><span/><span/><img src="/kit-mei-dashboard.png" alt="Dashboard do Kit Financeiro para MEI"/></div><div className={styles.floatCard}><span>Visão do negócio</span><strong>Lucro e pendências em segundos</strong></div></div></section>
    <section className={styles.problem}><p className={styles.sectionLabel}>Pare de trabalhar no escuro</p><h2>Seu negócio precisa de números claros, não de mais complicação.</h2><div className={styles.benefitGrid}>{benefits.map(([title,text],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className={styles.inside}><div className={styles.insideCopy}><p className={styles.sectionLabel}>Tudo em um único kit</p><h2>Transforme lançamentos simples em informações úteis.</h2><p>Você preenche os movimentos do dia a dia. A planilha atualiza os controles e mostra o resultado automaticamente.</p><ul>{included.map(item=><li key={item}><span>✓</span>{item}</li>)}</ul><BuyButton/></div><div className={styles.insideVisual}><img src="/kit-mei-precificacao.png" alt="Calculadora de precificação do kit"/><div><small>PREÇO SUSTENTÁVEL</small><strong>Custos, taxas e margem considerados</strong></div></div></section>
    <section className={styles.preview}><div className={styles.sectionHeading}><p className={styles.sectionLabel}>Veja por dentro</p><h2>Uma estrutura completa e fácil de reconhecer.</h2><p>As telas indicam o que deve ser preenchido e deixam os resultados visíveis.</p></div><div className={`${styles.previewTrack} ${fixes.previewTrack}`}>{previews.map(([src,alt])=><figure key={src}><img src={src} alt={alt} loading="lazy"/><figcaption>{alt}</figcaption></figure>)}</div></section>
    <section className={styles.steps}><p className={styles.sectionLabel}>Comece em três passos</p><h2>Abra, personalize e acompanhe.</h2><ol><li><span>01</span><div><strong>Configure</strong><p>Informe o negócio, o ano e ajuste as categorias.</p></div></li><li><span>02</span><div><strong>Registre</strong><p>Adicione receitas, despesas, valores e vencimentos.</p></div></li><li><span>03</span><div><strong>Decida</strong><p>Use o dashboard e a precificação para orientar suas escolhas.</p></div></li></ol></section>
    <section className={styles.faq}><div><p className={styles.sectionLabel}>Perguntas frequentes</p><h2>Antes de começar.</h2></div><div>{[['Preciso entender de Excel?','Não. Os campos de preenchimento são indicados e os resultados aparecem automaticamente.'],['Funciona no celular?','Pode ser aberto em aplicativos compatíveis, mas gráficos e fórmulas têm melhor experiência no computador.'],['É uma assinatura mensal?','Não. O valor de R$ 37,90 é um pagamento único.'],['Substitui um contador?','Não. O kit ajuda na organização, mas não substitui orientação contábil ou fiscal.']].map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section className={styles.finalCta}><div><p className={styles.sectionLabel}>Organize o dinheiro do negócio</p><h2>Comece hoje com mais clareza financeira.</h2><p>Controle, acompanhe e tome decisões com informações organizadas.</p></div><div><strong><span>R$</span> 37,90</strong><small>pagamento único</small><BuyButton/></div></section>
  </main><footer className={styles.footer}><a href="/"><img src={siteConfig.logoPath} alt="Ronas Tech" width="43" height="40"/></a><p>© {new Date().getFullYear()} Ronas Tech. Todos os direitos reservados.</p><div><a href="/politica-de-privacidade">Privacidade</a><a href="/termos-de-uso">Termos</a></div></footer>
</div>}

export default KitFinanceProductPage
